### ISSUE TITLE
LoginFailureException

### ISSUE THREAD

**Issue by MarianoCordoba** [mgp25/Chat-API#1558]
I was using Chat-API for a while, and now, when I try to login I got LoginFailureException.

```
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="5493584252381">?�5493584252381~i���j�Oٻ����1453757687</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>�U@�u�RO�������ɈJ</challenge>

tx  <response>�;oVBim��F?e.��þ�I>�������zX>9����</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

exception 'LoginFailureException' in C:\Dev\whatsapp-premier\src\Server\vendor\whatsapp\chat-api\src\Login.php:53
Stack trace:
#0 C:\Dev\whatsapp-premier\src\Server\vendor\whatsapp\chat-api\src\whatsprot.class.php(279): Login->doLogin()
#1 C:\Dev\whatsapp-premier\src\Server\src\App\App.php(42): WhatsProt->loginWithPassword('b6m79UPDXZUToat...')
#2 C:\Dev\whatsapp-premier\src\Server\run.php(7): App\App->start()
#3 {main}
```

And when I checked if my number is blocked using ```blockChecker.php``` I got
```
sdtClass Object
(
  [status] => fail
  [reason] => old_version
)
```

### Update
My code:
```
require_once __DIR__ . '/../../vendor/whatsapp/chat-api/src/whatsprot.class.php';

class App 
{
  public function start() {
    $this->wp = new \WhatsProt(
        $this->conf->get('user_login'),
        $this->conf->get('user_nickname'),
        $this->conf->get('debug'),
        $this->conf->get('log')
    );

    $this->events = new Events($this->wp, $this->db);
    $this->events->setEventsToListenFor($this->events->activeEvents);

    try {
        $this->wp->loginWithPassword($this->conf->get('user_password'));
    } catch (\Exception $ex) {
        echo $ex->getMessage();
    }
  }
}
```

Any solution?

**Comment by mgp25** [comment]
Really? What could `old_version` means? Common sense is telling to update source...
