### ISSUE TITLE
Working before, but now blocked even after using new account

### ISSUE THREAD

**Issue by mands72** [mgp25/Chat-API#1581]
Dear all,
I've been using this project for having a second way to send me a couple information about device temperatures if they reach a limit. This was working fine for months until a couple days ago. It first startet with my account being blocked. After I registered another phone number it worked for a day, but just this morning I got another "Your number is blocked" when checking it with the examples/blockChecker.php

Attached is my code, I'm using selfmade job-files which the script is looking for and later after scanning the folder sending the messages. Is there maybe something wrong with polling or whatever else? I would be verry happy if someone could take a look into it. Maybe it's not an API issue but just something I'm doing wrong, but since it was working for months and now isn't working anymore I'm a bit lost here (+ yes, already pulled latest commit from here).

Thank you,
Matt

```
<?php
	$username = "***";
	$password = "***";
	$from	  = "***";
	$debug = true;
	$ROOT = '/var/www/WhatsAPI';
	$dir = glob($ROOT.'/_queue/*');
	uasort($dir, "oldest");
	
	$dir = array_reverse($dir);
	
	touch('/var/log/WhatsAPI.last');

	if (count($dir)> 0)
	{
		$w = new WhatsProt($username, $from, $debug);
		$events = new MyEvents($w);
		$events->setEventsToListenFor($events->activeEvents);

		$w->connect();
		$w->loginWithPassword($password);
		$w->sendGetServerProperties();
		$w->sendClientConfig();

		foreach($dir as $file) 
		{				
			$filename = $ROOT.'/_queue/'.basename($file);
			$handle = fopen($filename, "r");
			if ($handle)
			{
				while (($line = fgets($handle)) !== false)
				{
					if(substr( $line, 0, 7 ) === "TARGET=")
					{
						$target = str_replace(array("\r", "\n"), "", substr($line, 7, strlen($line)));
					}
					else if(substr( $line, 0, 5 ) === "PATH=")
					{
						$path = str_replace(array("\r", "\n"), "", substr($line, 5, strlen($line)));
					}
					else if(substr( $line, 0, 5 ) === "FROM=")
					{
						$fromFile = str_replace(array("\r", "\n"), "", substr($line, 5, strlen($line)));
						if($from != $fromFile)
						{
							$from = $fromFile;
							$w->sendAvailableForChat($from);
						}
					}
					else if(substr( $line, 0, 4 ) === "MSG=")
					{
						$msg = br2nl(substr($line, 4, strlen($line)));
					}
				}
				fclose($handle);
				rename($ROOT.'/_queue/'.basename($file), $ROOT.'/_sent/'.basename($file));
				
				if (isset($msg) && !empty($msg) && isset($path) && !empty($path))
				{
					$ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
					if ($ext == 'mp4')
					{
						$w->sendMessageVideo($target, $path, false, 0, '', $msg);
					}
					else if ($ext == 'jpg' || $ext == 'png')
					{
						$w->sendMessageImage($target, $path, false, 0, '', $msg);
					}
				}
				else if (isset($msg) && !empty($msg))
				{
					$w->sendMessage($target, $msg);
				}
				else if (isset($path) && !empty($path))
				{
					$ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
							
					if ($ext == 'mp4')
					{
						$w->sendMessageVideo($target, $path);
					}
					else if ($ext == 'jpg' || $ext == 'png')
					{
						$w->sendMessageImage($target, $path);
					}
					else if ($ext == 'mp3')
					{
						$w->sendMessageAudio($target, $path);
					}
				}
			}
		}
		
		$i = 1;
		while ($i <= 15)
		{
			$w->pollMessage();
			echo 'Timestamp: '.time()."\n";
			$i++;
		}
	}
```

```
root@raspberrypi2:/var/www/WhatsAPI# php check.php
<p>WooHoo!, Phone number *** connected successfully!</p>tx  <stream:features></stream:features>

tx  <auth user="***" mechanism="WAUTH-2">42c***</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>c2***</challenge>

tx  <response>66***</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /var/www/WhatsAPI/src/Login.php:54
Stack trace:
#0 /var/www/WhatsAPI/src/whatsprot.class.php(286): Login->doLogin()
#1 /var/www/WhatsAPI/check.php(55): WhatsProt->loginWithPassword('6***')
#2 /var/www/WhatsAPI/check.php(13): CheckFolder()
#3 {main}
  thrown in /var/www/WhatsAPI/src/Login.php on line 54
```

**Comment by mgp25** [comment]
Check wiki flow: https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#whatsapp-workflow

And you are running outdated code

Regards
