### ISSUE TITLE
Invalid Token 120 - When Syncing Contacts

### ISSUE THREAD

**Issue by cooler-farmer** [mgp25/Chat-API#1583]
Hey, I get the following error when I try to sync my contacts: 

```
BinTreeNodeReader->readListSize: Invalid token 120
#0 /var/www/WhatsApp/src/BinTreeNodeReader.php(284): BinTreeNodeReader->readListSize(120) 
#1 /var/www/WhatsApp/src/BinTreeNodeReader.php(43): BinTreeNodeReader->nextTreeInternal() 
#2 /var/www/WhatsApp/src/whatsprot.class.php(2081): BinTreeNodeReader->nextTree('\xC0\x05\x87A\xE8\xE7Cr\x8E\xEA\xF8\xDEu\xB9\r...') 
#3 /var/www/WhatsApp/src/whatsprot.class.php(311): WhatsProt->processInboundData('\xC0\x05\x87A\xE8\xE7Cr\x8E\xEA\xF8\xDEu\xB9\r...') 
#4 /var/www/WhatsApp/src/whatsprot.class.php(1802): WhatsProt->pollMessage() 
#5 /var/www/WhatsApp/src/whatsprot.class.php(1979): WhatsProt->waitForServer('07') 
#6 /var/www/WhatsApp/examples/sendMessage.php(52): WhatsProt->sendSync(Array) 
#7 {main}
```

using this command: `$w->sendSync($contacts, null, 0);`

Debug log:

```
tx  <stream:features></stream:features>

tx  <auth user="49XXXX32" mechanism="WAUTH-2">d9dfaaf63439373131xxxxxxxxx43534333335303038</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>7458e8373bb1xxxxxxxxx04228</challenge>

tx  <response>21c20d08dfcc09a375exxxxxxxxxxxxxxxxffab84299bc7ea123e43180ef2c25c01cbbeb0e1900b89c36e0b6a9</response>

rx  <success t="1454335009" props="4" kind="free" status="active" creation="1454332250" expiration="4444444444">0953d65377xxxxxxxxxdae68f4a0ed23e</success>

tx  <presence name="Vertretungsplan" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="04" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="05" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="full" context="registration" sid="sync_sid_full_36bdaaca-e116-4b26-be32-d874a4bf2db1" index="0" last="true">
tx      <user>+491xxxxx6192</user>
##TRUNCATED##
tx      <user>+491xxxxxx51</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="497xxxxx2@s.whatsapp.net"></presence>

rx  <iq from="49XXXX32@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="49XXXX32@s.whatsapp.net" type="error" id="03">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="dSfrx_DJ9iy:APA91bcXhTd7HVl4udldURahp7Vt6NPnR3uuSWBUsWSCtY9Dje9sQTjN3ueJtg1WzUe76x_bNBaR-7bxpT2Dm1N2M_s7EXLMzwZ_nCDfGwSp7V0_C_vh6TAi8IrNZOyoX68vgNhVAY0s"></config>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <config platform="gcm" id="dSfrx_DJ9iy:APA91bcXhTd7HVl4udldURahp7Vt6NPnR3uuSWBUsWSCtY9Dje9sQTjN3ueJtg1WzUe76x_bNBaR-7bxpT2Dm1N2M_s7EXLMzwZ_nCDfGwSp7V0_C_vh6TAi8IrNZOyoX68vgNhVAY0s"></config>
rx  </iq>
```

**Comment by cooler-farmer** [comment]
#1575
