### ISSUE TITLE
PHP Fatal Error: Need to register again

### ISSUE THREAD

**Issue by BloBBlub20** [mgp25/Chat-API#1660]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X ] You are using PHP > 5.6
- [X ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X ] You have checked if someone has already asked the same issue you have.
- [X ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X ] Is not a programming question.
- [ X] You are using latest Chat API code.

Hi Guys,

i have a problem. From time to time, my number get's 'inactive' or something. The log says: "Request new password and try again". If i remove my WhatsApp account, and register it again, problem is most of the time solved. But not always..  Any solution? 

i know 

````
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
````

Means that number is blocked, but that seems not the case, cause i need to register again.

### Error

````
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /home/whatsappserv/api/assets/whatsapp/Registration.php:89
Stack trace:
#0 /home/whatsappserv/api/server/helpers/WhatsApp.php(142): Registration->checkCredentials()
#1 /home/whatsappserv/api/server/helpers/WhatsApp.php(78): Server\Helpers\WhatsApp->loginToWhatsApp('bz5r9isK/gfZiDG...')
#2 /home/whatsappserv/api/server/tasks/MainTask.php(49): Server\Helpers\WhatsApp->init()
#3 [internal function]: Server\Task\MainTask->startServerAction(Array)
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /home/whatsappserv/api/server/start-whatsapp.php(76): Phalcon\Cli\Console->handle(Array)
#6 {main}
  thrown in /home/whatsappserv/api/assets/whatsapp/Registration.php on line 89
root@chatapi:/home/whatsappserv/api/server#
````

### Debug log
Post your debug log below:

```xml
root@chatapi:/home/whatsappserv/api/server# php start-whatsapp.php 295 true
tx  <stream:features></stream:features>

tx  <auth user=“MOBILENUMBER” mechanism="WAUTH-2">891e4047333136313737313130303192435e7feee0e64b33b6d235e581116b30cf782c31343536353933353031</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>057bc9f27a289d27e4a36a1c975e7129a1933f3c</challenge>

tx  <response>57a1394f7d16561940c523cfef8ec566fc3bc936d8286c28a232850b4ddff6d47521aa57090546fac31d0718588f214d2532b4e90c368ae3a1027dc69c6447ee156686a1c524895131a9d0d06c</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /home/whatsappserv/api/assets/whatsapp/Registration.php:89
Stack trace:
#0 /home/whatsappserv/api/server/helpers/WhatsApp.php(142): Registration->checkCredentials()
#1 /home/whatsappserv/api/server/helpers/WhatsApp.php(78): Server\Helpers\WhatsApp->loginToWhatsApp('bz5r9isK/gfZiDG...')
#2 /home/whatsappserv/api/server/tasks/MainTask.php(49): Server\Helpers\WhatsApp->init()
#3 [internal function]: Server\Task\MainTask->startServerAction(Array)
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /home/whatsappserv/api/server/start-whatsapp.php(76): Phalcon\Cli\Console->handle(Array)
#6 {main}
  thrown in /home/whatsappserv/api/assets/whatsapp/Registration.php on line 89
root@chatapi:/home/whatsappserv/api/server#

```

**Comment by 0xTryCatch** [comment]
Your number has been blocked by WhatsApp

**Comment by BloBBlub20** [comment]
Hi, it is not logic.. This happens from time to time, and when i register myself again, problem is most of time solved.. Something wrong in the flow?

**Comment by 0xTryCatch** [comment]
Try ```blockChecker.php```
