### ISSUE TITLE
Undefined offset 1 When trying to send image to group

### ISSUE THREAD

**Issue by AndreySlashman** [mgp25/Chat-API#1709]
Hello!
When trying to send picture to the group, sometimes, i reveive the following error:

```
Notice: Undefined offset: 1
```

Error trace:

```
#0 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/mediauploader.php(36): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/panel-...', 36, Array)
#1 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/mediauploader.php(88): WhatsMediaUploader::sendData('mmi731.whatsapp...', 'POST https://mm...', '--zzXXzzYYzzXXz...', '/var/www/panel-...', Array, '\r\n--zzXXzzYYzzX...')
#2 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/mediauploader.php(53): WhatsMediaUploader::getPostString('/var/www/panel-...', 'https://mmi731....', Array, '919307067602-14...', '919307067602')
#3 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(2519): WhatsMediaUploader::pushFile(Object(ProtocolNode), Array, Array, '919307067602')
#4 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/handlers/IqHandler.php(110): WhatsProt->processUploadResponse(Object(ProtocolNode))
#5 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(2376): IqHandler->Process()
#6 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(2084): WhatsProt->processInboundDataNode(Object(ProtocolNode))
#7 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(311): WhatsProt->processInboundData('\x80\x00\x99\x94\xDF$7l\xC7\x07\xECp>y\x8D...')
#8 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(1803): WhatsProt->pollMessage()
#9 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(2982): WhatsProt->waitForServer('0e')
#10 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(2677): WhatsProt->sendRequestFileUpload('DD2q7IIvjeiYtBV...', 'image', 72054, '/var/www/panel-...', '919307067602-14...', 'kjhgfds')
#11 /var/www/jenkins-bot/vendor/whatsapp/chat-api/src/whatsprot.class.php(1390): WhatsProt->sendCheckAndSendMedia('gaufrette://fil...', 5242880, '919307067602-14...', 'image', Array, false, 'kjhgfds')
```

But this occurs only sometimes, for example, 10 mins after receiving this error I were able to send the same message successfully

### Debug log
```xml
tx  <ack to="79280006909@s.whatsapp.net" class="notification" id="2577176196" type="features"></ack>

rx  <notification from="79280006930@s.whatsapp.net" type="picture" id="223644306" offline="0" notify="Бено" t="1457587351">
rx    <set jid="79280006930@s.whatsapp.net" id="1457587350"></set>
rx  </notification>

tx  <ack to="79280006930@s.whatsapp.net" class="notification" id="223644306" type="picture"></ack>

rx  <notification from="79280010204@s.whatsapp.net" type="picture" id="1348285767" offline="0" notify="001" t="1457590127">
rx    <set jid="79280010204@s.whatsapp.net" id="1457590127"></set>
rx  </notification>

tx  <ack to="79280010204@s.whatsapp.net" class="notification" id="1348285767" type="picture"></ack>

rx  <notification from="79280010204@s.whatsapp.net" type="picture" id="3567757776" offline="0" notify="001" t="1457594077">
rx    <set jid="79280010204@s.whatsapp.net" id="1457594077"></set>
rx  </notification>

tx  <ack to="79280010204@s.whatsapp.net" class="notification" id="3567757776" type="picture"></ack>

rx  <notification from="79280010204@s.whatsapp.net" type="picture" id="3691051889" offline="0" notify="001" t="1457594436">
rx    <set jid="79280010204@s.whatsapp.net" id="1457594435"></set>
rx  </notification>

tx  <ack to="79280010204@s.whatsapp.net" class="notification" id="3691051889" type="picture"></ack>

rx  <notification from="79280007439@s.whatsapp.net" type="features" id="2144357278" offline="0" t="1457595854">
rx    <feature>
rx      <encrypt_audio value="allow"></encrypt_audio>
rx      <encrypt_video value="allow"></encrypt_video>
rx    </feature>
rx  </notification>

tx  <ack to="79280007439@s.whatsapp.net" class="notification" id="2144357278" type="features"></ack>

rx  <notification from="79280008239@s.whatsapp.net" type="picture" id="2782394699" offline="0" notify="😜" t="1457596009">
rx    <set jid="79280008239@s.whatsapp.net" id="1457596008"></set>
rx  </notification>

tx  <ack to="79280008239@s.whatsapp.net" class="notification" id="2782394699" type="picture"></ack>

rx  <iq from="s.whatsapp.net" type="result" id="0e">
rx    <media url="https://mmi731.whatsapp.net/u/TXQVtAnW7zhAWMSxWR7cOVAn72wABS2yIR6YXQ/AqT52pY3gzuU3sIacha4KgiGc7U-RYf9mYeNQBpLaxUf" ip="169.53.29.154"></media>
rx  </iq>

Notice: Undefined offset: 1
```

**Comment by dcardosoa** [comment]
Do you use the last commit?

**Comment by AndreySlashman** [comment]
Nope, Im using the latest release, v3.2

I see that WhatsMediaUploader::sendData was altered in the latest commit, i will update on dev-master and try further

Thank you

**Comment by JJF2** [comment]
I have the same issue here.
Already applied ba36fb0 but don't seem resolutive.
Some images cause the issue and other not. Didn't found a rule.

**Comment by AndreySlashman** [comment]
You need the latest commit, https://github.com/mgp25/Chat-API/commit/1c4223138e4fdb0625deea4119dbffabc7f10687 this one

The issue seems to be fixed in this very commit
