### ISSUE TITLE
Error while opening a connection:: 'SQLSTATE[HY000] [14] unable to open database file' in 

### ISSUE THREAD

**Issue by kadnan** [mgp25/Chat-API#1784]
I installed the library via `composer` in read-only mode. When running the code:
``
$w = new WhatsProt($username, $nickname, $debug);
$w->connect();
``
Which gives error:
```

] Logging in as 'mFolder Agent' (xx) 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in /Applications/MAMP/htdocs/clients/mFolder/whatsappchat/Server/vendor/whatsapp/chat-api/src/SqliteMessageStore.php:19 Stack trace: #0 /Applications/MAMP/htdocs/clients/mFolder/whatsappchat/Server/vendor/whatsapp/chat-api/src/SqliteMessageStore.php(19): PDO->__construct('sqlite:/Applica...', NULL, NULL, Array) #1 /Applications/MAMP/htdocs/clients/mFolder/whatsappchat/Server/vendor/whatsapp/chat-api/src/whatsprot.class.php(126): SqliteMessageStore->__construct('xx') #2 /Applications/MAMP/htdocs/clients/mFolder/whatsappchat/Server/connect.php(19): WhatsProt->__construct('xx', 'mFolder Ag...', false) #3 {main} thrown in/Applications/MAMP/htdocs/clients/mFolder/whatsappchat/Server/vendor/whatsapp/chat-api/src/SqliteMessageStore.php on line 19
```

I guess because it's generating the file in a read-only folder. How can I change `wadata` path?

**Comment by mgp25** [comment]
In the constructor `public function __construct($number, $nickname, $debug = false, $log = false, $datafolder = null)`

Regards
