### ISSUE TITLE
I'm having problems logging in

### ISSUE THREAD

**Issue by Pudins** [mgp25/Chat-API#1850]
Hello friends!
I'm having problems logging in, it seems that the pass is changed from time to time, as when trying to log in after a time off the login error, I have to redo the number activation for a new password, follow my code and debug , I thank the help.

**Code:**
```php
`require_once './src/whatsprot.class.php';
require_once './src/events/MyEvents.php';

//Change the time zone if you are in a different country
date_default_timezone_set('America/Sao_Paulo');

////////////////CONFIGURATION///////////////////////
////////////////////////////////////////////////////
$username = 'XXXXXXXXX';
$password = 'XXXXXXXX';
$nickname = 'Pudins';
$debug = true;
/////////////////////////////////////////////////////


$w = new WhatsProt($username, $nickname, $debug);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents);
$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

while ( true )
{
    $w->pollMessage();
    if (time()%60 == 0) $w->sendPing();
    sleep(1);
}
```

**Debug:**
```xml
WooHoo!, Sistema rodando com sucesso!tx  <stream:features></stream:features>

tx  <auth user="XXXXXXXXXX" mechanism="WAUTH-2">4f8c9e97353536323832303635383730a686950447ccccc89a341198bfe37ea7c28f662c31343631303634373036</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b9002004f09a6336aa7fd01e4b0a09fa6301a93f</challenge>

tx  <response>50149422da636b22cc17d88ab7479bb543eced1cf6928cea71d62fecee4cdee204f268c4491a36d01c342be9a9dce03af9505587b8c73e40a4308628a621d2cc8ac69c21d6562487acc34f755cf6</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

Maudito Morphy!, Algo deu errado!
Fatal error: Uncaught exception 'LoginFailureException' in D:\www\projetos\pudins\cron\src\Login.php:54
Stack trace:
#0 D:\www\projetos\pudins\cron\src\whatsprot.class.php(286): Login->doLogin()
#1 D:\www\projetos\pudins\cron\WhatsCron.php(24): WhatsProt->loginWithPassword('DfpXrvxKpfZbfOk...')
#2 {main}
  thrown in D:\www\projetos\pudins\cron\src\Login.php on line 54
```

**Comment by mgp25** [comment]
Your number is blocked

```xml
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by Pudins** [comment]
For you in my code is something that can calsar the lock? I can reactivate the number reregistering that's what most astonishes me!
For if he is locked it was not to reregister correct?

**Comment by yniwly43** [comment]
What do you mean?

1. What happens when you use the SIM in your phone? What message do you see from Whatsapp - suspended, not authorized to use the service, or it works?
2. When you re-register, what happens? It works?

**Comment by softcode2** [comment]
the main problem now if you register new numbers it will blocked directly when you doing any process on this api , maybe this problem it will fix on next version .
