### ISSUE TITLE
New number got shutdown

### ISSUE THREAD

**Issue by samuelg78** [mgp25/Chat-API#1871]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [ x] You are using latest Chat API code.

### Error
Post your error below:
Number running for 24 hour then got shutdown response from whatsapp, subsequent attempt to login again and got the not-authorized response.
```xml
tx  <stream:features></stream:features>

tx  <auth user="xxxxxxxxx" mechanism="WAUTH-2">acececee36353833373238303034ca33
ceed46147e730c1d91a40f8493d78ba2d6db31343631383836353533</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>4d684205c10d0074973c0f36431a48c2fe26ecbc</challenge>

tx  <response>17bb652ca5f53a2f1b36dafdd10bf97c594bcb0be156d229b9080571e4e67803bc
a0d4a1d5f470c2d10a8df3ae9c5658777970208e2b300c197cb1f1421578e64a4dceff48bed61de0
24009f</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\Chat-
API-master\src\Login.php:54
```

### Debug log
```xml
tx  <stream:features></stream:features>

tx  <auth user="xxxxxxxxx" mechanism="WAUTH-2">98ff0bfa36353833373238303034b9a
de0431ca5dda3d75fe0abe6a7fed7ab12bea31343631383633323333</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>11d317bdbcf8e07867f0aa089d2151e5c6956119</challenge>

tx  <response>c9f67ff1051d31f29cca75963ce7d25ef6f3bda02a922f167414aac7abd1da4ad
6e65e8135aa0d56742114dbe6b3e74f29d180b3ec6a8cc3634761cb2fe5d2c8e6d20aa454a35c0f
9e53ce</response>

rx  <success t="1461863235" props="5" kind="free" status="active" creation="146
782848" expiration="4444444444">ca33ceed46147e730c1d91a40f8493d78ba2d6db</succe
s>

tx  <presence name="WhatsAPI Test" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="04" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

tx  <iq id="06" xmlns="w:b" type="get" to="s.whatsapp.net">
tx    <lists></lists>
tx  </iq>

tx  <iq id="07" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="08" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_d5553bc3-880b
487c-a024-ea69858fcc3e" index="0" last="true">
tx      <user>+xxxxxxxxx</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="xxxxxxxxx@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <props version="5">
rx      <prop name="allow" value="all"></prop>
rx      <prop name="archive" value="1"></prop>
rx      <prop name="audio_opus" value="1"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="call" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="doc_types" value="csv,doc,docx,pdf,ppt,pptx,rtf,txt,xls,xls
"></prop>
rx      <prop name="e2e_audio" value="0"></prop>
rx      <prop name="e2e_blists" value="1"></prop>
rx      <prop name="e2e_groups" value="1"></prop>
rx      <prop name="e2e_images" value="1"></prop>
rx      <prop name="e2e_video" value="0"></prop>
rx      <prop name="e2e_voip" value="1"></prop>
rx      <prop name="file_max_size" value="100"></prop>
rx      <prop name="force_long_connect" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="identity_verification" value="1"></prop>
rx      <prop name="image_max_edge" value="1600"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx      <prop name="max_participants" value="257"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="media" value="64"></prop>
rx      <prop name="media_max_autodownload" value="32"></prop>
rx      <prop name="mspes" value="1"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="plaintext_disabled" value="1"></prop>
rx      <prop name="plaintext_reenable_threshold" value="5"></prop>
rx      <prop name="qr" value="1"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="small_call_btn" value="1"></prop>
rx      <prop name="source" value="1"></prop>
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="wbarchive" value="1"></prop>
rx    </props>
rx  </iq>

rx  <iq from="xxxxxxxxx@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="06">
rx    <lists></lists>
rx  </iq>

rx  <iq from="xxxxxxxxx@s.whatsapp.net" type="error" id="07">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="g.us" type="result" id="05">
rx    <groups></groups>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="03">
rx    <config platform="gcm" id="1E80E_CD3W5:APA91bJ4Eq6XJnvUPB8LR5kLla0OdztjpA
q1anLWomHPY2HWLvV9SHPwlLOzZgEyDXTfB_8qr9S-eV2HSbnO2r9E_jEwdmRcQH_huyYb1Ij1EO_c_
pXB0H1wQKqrMRcOVESUKs5ZgJ"></config>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="1E80E_CD3W5:APA91bJ4Eq6XJnvUPB8LR5kLla0OdztjpA
q1anLWomHPY2HWLvV9SHPwlLOzZgEyDXTfB_8qr9S-eV2HSbnO2r9E_jEwdmRcQH_huyYb1Ij1EO_c_
pXB0H1wQKqrMRcOVESUKs5ZgJ"></config>
rx  </iq>

rx  <iq from="xxxxxxxxx@s.whatsapp.net" type="result" id="08">
rx    <sync index="0" sid="sync_sid_full_d5553bc3-880b-487c-a024-ea69858fcc3e"
ast="true" version="1461863236115638">
rx      <in>
rx        <user jid="xxxxxxxxx@s.whatsapp.net">+xxxxxxxxx</user>
rx      </in>
rx    </sync>
rx  </iq>

rx  <presence from="xxxxxxxxx@s.whatsapp.net"></presence>

rx  <chatstate from="xxxxxxxxx@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <chatstate from="xxxxxxxxx@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <chatstate from="xxxxxxxxx@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="xxxxxxxxx@s.whatsapp.net" type="text" id="B96F2AA28881B5D2E
7A6C36F934AE" t="1461863298" notify="......">
rx    <enc v="2" type="pkmsg">3308a0cc8a071221055e67c10c5ba0d0445f0c062c2b6da14
7715921416cd85e5e7737cf17628cd481a2105057e247f80ff25c718fe963b1c46f24fe6294a924
3279001719b305c732a8142262330a21051e2c8656f2ab0a8dfbe9c7956661dae3145627d86732e
c35af033f8d9d4044a1003180022307445ace75825951c9528921c1aa7ee721160691721f8c0d1f
eb3fcd4f96c3f80f453607beeee043d124c948d9edefe910d6016482196907288694b9d70530ba8
01</enc>
rx  </message>

tx  <ack to="xxxxxxxxx@s.whatsapp.net" class="message" id="B96F2AA28881B5D2EC7
6C36F934AE" t="1461863298"></ack>


-> Decrypted Message: How are you?

tx  <receipt type="read" to="xxxxxxxxx@s.whatsapp.net" id="B96F2AA28881B5D2EC7
6C36F934AE" t="1461863298"></receipt>

 --->xxxxxxxxx^xxxxxxxxx^......^2016.04.29 06:38 am^1461883098^Text^How are y
u bro?

rx  <ack from="xxxxxxxxx@s.whatsapp.net" class="receipt" type="read" id="B96F2
A28881B5D2EC7A6C36F934AE"></ack>

tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="09" t="1461863359"></iq>

tx  <iq id="0a" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="0a" t="1461863420"></iq>

rx  <presence from="xxxxxxxxx@s.whatsapp.net" type="unavailable" last="1461863
33"></presence>

tx  <iq id="0b" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="0b" t="1461863494"></iq>

tx  <iq id="0c" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="0c" t="1461863556"></iq>

tx  <iq id="0d" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="0d" t="1461863603"></iq>


tx  <iq id="0e" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


rx  <iq from="s.whatsapp.net" type="result" id="0e" t="1461863664"></iq>

tx  <iq id="0f" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


rx  <iq from="s.whatsapp.net" type="result" id="0f" t="1461863725"></iq>

rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>
```

[Error: pollMessage()]: Connection Closed!

**Comment by gratbrav** [comment]
maybe whatsapp changed the password. have you try to register the number again?

**Comment by marcelogabrielmartinez** [comment]
Please check https://github.com/mgp25/Chat-API/issues/1872

**Comment by samuelg78** [comment]
@mgp25 Please advice on the frequency on the ping, sendsync, sendGetStatuses, sendGetProfilePicture and re-connect.

**Comment by samuelg78** [comment]
@mgp25 I tried 2 pings and reconnect but got the error

```xml

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">93c05f8136303137373631353339373
f1a1429f7dbe778378f55a6b85291e6c729e04e31343632333331343631</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>b713d8cdfc441fa6b1c8756b3753727d08f439f3</challenge>

tx  <response>eb0dcd885dc30ec7a75153d73e0aa3f0814ac97af557484846715d59dc1ecd46ec
c08f5bda93303252157459180825893ee17597ebb9cedcc4b525713004ebff19af6a67e67bd0c36f
87b559a9</response>

rx  <success t="1462331462" props="5" kind="free" status="active" creation="1462
330553" expiration="4444444444">3519511017f2219a672426d91add9f1d4315ed51</succes
s>

tx  <presence name="WAWA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_81f1f53e-feef-
4ad3-a99c-539ddd00ded6" index="0" last="true">
tx      <user>+XXXXXXXXXXX</user>
tx      <user>+XXXXXXXXXXX</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="60177615397@s.whatsapp.net"></presence>

rx  <iq from="60177615397@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="60177615397@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_81f1f53e-feef-4ad3-a99c-539ddd00ded6" l
ast="true" version="1462330619943694">
rx      <in>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx      </in>
rx    </sync>
rx  </iq>


XXXXXXXXXXX@s.whatsapp.net exists

XXXXXXXXXXX@s.whatsapp.net exists
tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="04">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.n
et">
tx    <picture type="preview"></picture>
tx  </iq>

tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="06">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="07" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.
net">
tx    <picture type="preview"></picture>
tx  </iq>



[] 11:11:02am Start Now:
rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="ob99q_s6sqI:APA91beUqB6yJ7pCbuLmu2937JPmruuIZA3
xLpjzGp72edDxFXmUOaTygaKHlKB8fN21hQ_VuJp7-8bEQoaSy3n00_y1k8PMtsX_NZ4uM6d2VHk_c_c
u16oKXeuugKAHXirDYuMOhB1I"></config>
rx  </iq>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></
presence>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="error" id="07">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <status>
rx      <user jid="XXXXXXXXXXX@s.whatsapp.net" t="1460903044">Hey there! I am usi
ng WhatsApp.</user>
rx    </status>
rx  </iq>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="result" id="05">
rx    <picture id="1447575006" type="preview"> 2176 byte data</picture>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="06">
rx    <status>
rx      <user jid="XXXXXXXXXXX@s.whatsapp.net" t="1458350655">Hey there! I am us
ing WhatsApp.</user>
rx    </status>
rx  </iq>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1462331
405"></presence>


11:16:53am.....[keep-alive] Ping sent.....
tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="08" t="1462331814"></iq>


11:22:50am.....[keep-alive] Ping sent.....
tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="09" t="1462332171"></iq>


.....Disconnected Manually.....
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">63d801be36303137373631353339373
519511017f2219a672426d91add9f1d4315ed5131343632333332353238</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>5eefd24079f3760a15b27e1f0e8b0829ca4c7f5b</challenge>

tx  <response>cb7b26d557abbd95d72db9991e30ef4ed6c2ca05ed62bc979bcc64a4ca863b33ef
964ae81ba2adc610ddfe9e68afd43adc6adc66b8ded13d1b2e0b9296649c70602b7582905688df82
41ddb02f</response>

rx  <success t="1462332529" props="5" kind="free" status="active" creation="1462
330553" expiration="4444444444">1d1710dc80e19cd99750176fd491bc48486fa428</succes
s>

tx  <presence name="WAWA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_ab8c039f-e479-
4e2f-8b73-f5f239c13a73" index="0" last="true">
tx      <user>+XXXXXXXXXXX</user>
tx      <user>+XXXXXXXXXXX</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="60177615397@s.whatsapp.net"></presence>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net" type="unavailable" last="1462331
405"></presence>

rx  <iq from="60177615397@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="60177615397@s.whatsapp.net" type="result" id="03">
rx    <sync index="0" sid="sync_sid_full_ab8c039f-e479-4e2f-8b73-f5f239c13a73" l
ast="true" version="1462330619943694">
rx      <in>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx        <user jid="XXXXXXXXXXX@s.whatsapp.net">+XXXXXXXXXXX</user>
rx      </in>
rx    </sync>
rx  </iq>


XXXXXXXXXXX@s.whatsapp.net exists

XXXXXXXXXXX@s.whatsapp.net exists
tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="04">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.n
et">
tx    <picture type="preview"></picture>
tx  </iq>

tx  <presence type="subscribe" to="XXXXXXXXXXX@s.whatsapp.net"></presence>

tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="06">
tx    <status>
tx      <user jid="XXXXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

tx  <iq id="07" type="get" xmlns="w:profile:picture" to="XXXXXXXXXXX@s.whatsapp.
net">
tx    <picture type="preview"></picture>
tx  </iq>



[] 11:28:50am Start Now:
rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="ob99q_s6sqI:APA91beUqB6yJ7pCbuLmu2937JPmruuIZA3
xLpjzGp72edDxFXmUOaTygaKHlKB8fN21hQ_VuJp7-8bEQoaSy3n00_y1k8PMtsX_NZ4uM6d2VHk_c_c
u16oKXeuugKAHXirDYuMOhB1I"></config>
rx  </iq>


11:31:49am.....[keep-alive] Ping sent.....
tx  <iq id="08" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


Warning: socket_write(): unable to write to socket [10053]: An established conne
ction was aborted by the software in your host machine.
 in C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php on line 2753

11:34:50am.....[keep-alive] Ping sent.....
tx  <iq id="09" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>


Warning: socket_write(): unable to write to socket [10053]: An established conne
ction was aborted by the software in your host machine.
 in C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php on line 2753

.....Disconnected Manually.....
[] Logging in as 'WAWA' (60177615397)

.....Connecting.....
tx  <stream:features></stream:features>

tx  <auth user="60177615397" mechanism="WAUTH-2">076426b436303137373631353339371
d1710dc80e19cd99750176fd491bc48486fa42831343632333333303730</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>808b5414c26d92d795f3994972525baa85ece49f</challenge>

tx  <response>d03bb2c6910e46f83f9b331bc83e727693f180131b091718eb58261be785145376
a79903571ae34e3f5f4f15d4526a999b8a08beae3750fe13c0c445424d8d9bea1c03bb28edec47c1
81e35b5b</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\Chat-
API-master\src\Login.php:54
Stack trace:
#0 C:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php(286): Login->doLogin(
)
#1 C:\xampp\htdocs\Chat-API-master\tests\whatsapp3.php(81): WhatsProt->loginWith
Password('7H/9GddvDEay6KQ...')
#2 {main}
  thrown in C:\xampp\htdocs\Chat-API-master\src\Login.php on line 54

```

**Comment by Sinnercito** [comment]
#1322
