### ISSUE TITLE
Problem Interactive Chat-API

### ISSUE THREAD

**Issue by aladin72002** [mgp25/Chat-API#2000]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X ] You are using PHP > 5.6
- [X ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X ] You have checked if someone has already asked the same issue you have.
- [X ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X ] Is not a programming question.
- [X ] You are using latest Chat API code.

### Error
I run Chat-API at 02:40 and get thats error at 09:40:12 , is there some thing wrong in my code, this is my main code

<?php
require_once 'include/DB_Functions.php';
require_once 'src/whatsprot.class.php';

set_time_limit(0);

	function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
	{
		$db = new DB_Functions();
		$db->setinsertpesan($mynumber, $from, $id, $type, $time, $name, $body);
	}
	

	function onPresenceAvailable($username, $from)
	{
		$dFrom = str_replace(['@s.whatsapp.net', '@g.us'], '', $from);
		echo "<$dFrom is online>\n\n";
	}
	
	function onPresenceUnavailable($username, $from, $last)
	{
		$dFrom = str_replace(['@s.whatsapp.net', '@g.us'], '', $from);
		echo "<$dFrom is offline>\n\n";
	}
	
	
	$target="YYYY";
	$username = 'XXXX';
	$identity = '0';
	$nickname = 'XXXXX';
	$password = "XXXXX";
	
	$w = new WhatsProt($username, $identity, $nickname, false);
	$w->eventManager()->bind("onGetMessage", "onMessage");
	$w->eventManager()->bind('onPresenceAvailable', 'onPresenceAvailable');
	$w->eventManager()->bind('onPresenceUnavailable', 'onPresenceUnavailable');
	
	$w->connect();
	$w->loginWithPassword($password);
	
	$w->sendGetServerProperties(); 
	$w->sendClientConfig(); 
	$sync = [$target];
	$w->sendSync($sync); 
	$w->pollMessage(); 
	$w->sendPresenceSubscription($target);
	
	$dbx = new DB_Functions();

	$varloop=0;
	$flagrnd=false;
	$rdm=0;
	
	while (true) {

		$start = time();
		$varloop=$varloop+1;
		
		
		$w->pollMessage();
		
		if (!$flagrnd){
			$rdm=mt_rand(700,1100);
			$flagrnd=true;
		}
		
		if ($rdm==$varloop){
			$rdmx=mt_rand(10,300);
			$w->sendPresenceSubscription($target);
			$w->sendMessage($target,"MSGID->".$rdmx. " \n ".(date('h:i:s')));
			
			$flagrnd=false;
			$varloop=0;
			
		}else {
			
			$messages = $w->getMessages();
			if (count($messages) > 0) {
					
				$idxx=$dbx->getID();
				$no=$dbx->getNumber();
			
				$msgxx=$dbx->getFeedback($idxx);
				
				if($msgxx!='0'){
					$rdmxx=mt_rand(10,300);
					$w->sendPresenceSubscription($no);
					$w->sendMessage($no,"MSGID->".$rdmxx."\n". $msgxx);
				}else{
					$rdmxx=mt_rand(10,300);
					$w->sendPresenceSubscription($no);
					$w->sendMessage($no,"MSGID->".$rdmxx."\n". "Format Tidak Dikenal");
				}
				
				
			
			}
		}
		
		$rdmxx2=mt_rand(3,5);
		print_r ((date('h:i:s'))."|".$rdmxx2."|".$varloop."\n");
		usleep($rdmxx2*1000000);
		
	}

?>

please help me.

### Debug log
09:37:59|4|769
rx  <iq from="s.whatsapp.net" type="result" id="4" t="1465587475"></iq>

09:38:03|4|770
09:38:09|5|771
09:38:16|3|772
09:38:21|4|773
09:38:27|3|774
09:38:32|5|775
09:38:39|5|776
09:38:46|4|777
09:38:52|3|778
09:38:57|5|779
tx  <presence type="unavailable"></presence>

tx  <stream:features></stream:features>

tx  <auth user="MyNumber" mechanism="WAUTH-2">56b86ad3363238333837323238363
9393349f8679d2a22d95a1fcc24a5e23c174731a172d731343635353837353435</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>9a839f2062c49ea92b2888467ae0d7af9433bd1b</challenge>

tx  <response>04625418d7196c1494ec76519aeb64cfcb256512b0e444178dea1b1ab8a2c5d00e
4d2c6c21a0dbf9a7fcbba7716688e56a78619f6027e3030a91b3dd1ebdbadfab78de66a649f9d8e5
813fb391d773</response>

rx  <success t="1465587541" props="5" kind="free" status="active" creation="1465
557976" expiration="4444444444">9cf8f448ce00be7500842ffe4c9987a51ce55e78</succes
s>

tx  <presence name="0" type="available"></presence>

tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

09:39:06|4|780
rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

09:39:10|3|781
rx  <presence from="MyNumber@s.whatsapp.net"></presence>

09:39:13|4|782
rx  <iq from="MyNumber@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

09:39:17|3|783
rx  <iq from="s.whatsapp.net" type="error" id="2">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

09:39:20|3|784
09:39:25|4|785
09:39:31|3|786
09:39:36|5|787
09:39:43|5|788
09:39:50|3|789
09:39:55|5|790
09:40:02|4|791
09:40:08|3|792
##### Suddenly Show This Massege
rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>

09:40:12|4|793
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connect
ion Closed!' in C:\xampp\htdocs\Chat-API\src\whatsprot.class.php:300
Stack trace:
#0 C:\xampp\htdocs\Chat-API\Chat-API.php(65): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\xampp\htdocs\Chat-API\src\whatsprot.class.php on line 300

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection C
losed!' in C:\xampp\htdocs\Chat-API\src\whatsprot.class.php:300
Stack trace:
#0 C:\xampp\htdocs\Chat-API\Chat-API.php(65): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\xampp\htdocs\Chat-API\src\whatsprot.class.php on line 300

##try to connect again  
C:\xampp\htdocs\Chat-API>php Chat-API.php
tx  <stream:features></stream:features>

tx  <auth user="MyNumber" mechanism="WAUTH-2">67d529f2363238333837323238363
939339cf8f448ce00be7500842ffe4c9987a51ce55e7831343635353837383538</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>9f603dc3f58429d6ee18a94b074ed73581f2e15c</challenge>

tx  <response>8dba6fd2218bd9ee7b2c774662b407b0fb5f6052fc10c93ca956bbbe926b87c934
5b8af8f9fb07dff5eab72ffd8051cd608897794cacd3d3801d6a105f94a198cde00ca0a5b2cbc55d
6ca2ae5f6ed9</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\
Chat-API\src\Login.php:54
Stack trace:
#0 C:\xampp\htdocs\Chat-API\src\whatsprot.class.php(287): Login->doLogin()
#1 C:\xampp\htdocs\Chat-API\Chat-API.php(42): WhatsProt->loginWithPassword('WyMg8d
Wi9td5m5H...')
#2 {main}
  thrown in C:\xampp\htdocs\Chat-API\src\Login.php on line 54

Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\WADac
en\src\Login.php:54
Stack trace:
#0 C:\xampp\htdocs\Chat-API\src\whatsprot.class.php(287): Login->doLogin()
#1 C:\xampp\htdocs\Chat-API\Chat-API.php(42): WhatsProt->loginWithPassword('WyMg8d
Wi9td5m5H...')
#2 {main}
  thrown in C:\xampp\htdocs\Chat-API\src\Login.php on line 54

**Comment by aladin72002** [comment]
@0xTryCatch let me know, how fix my code , so next time mynumber not Blocked

**Comment by lironsher** [comment]
I have the same issue. They are blocking after few connections even without writing any message.

Any ideas?

**Comment by mgp25** [comment]
Duplicate, wrong flow, read closed issues and documentation

**Comment by aladin72002** [comment]
@mgp25 i've follow workflow and read documentation.. and i'm still get blocked after 7 hours..is there a trick to tread my code so mynumber did'nt blocked

**Comment by mgp25** [comment]
@aladin72002 no, you havent, and here is a proof of it:

Sending node before getting success node:

```xml
WRONG ------> tx  <presence type="unavailable"></presence>

tx  <stream:features></stream:features>

tx  <auth user="MyNumber" mechanism="WAUTH-2">56b86ad3363238333837323238363
9393349f8679d2a22d95a1fcc24a5e23c174731a172d731343635353837353435</auth>
```

Please next time take some time to review your debug log becuase sometimes the answer is just in front of us

Regards
