### ISSUE TITLE
I follow the work flow but everytime blocked.

### ISSUE THREAD

**Issue by fcosystems** [mgp25/Chat-API#2061]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x ] You have checked if someone has already asked the same issue you have.
- [x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x ] Is not a programming question.
- [x ] You are using latest Chat API code.

### Error
I am not a spammer
I follow the work flow (I belive..) 
I have the las Chat-api //    const WHATSAPP_VER = '2.16.148';      
I have changed the ip address many times.

### Debug log
```xml
tx  <stream:features></stream:features>

tx  <auth user="573012919665" mechanism="WAUTH-2">cc701eb6353733303132393139363635d5773b0811310ac2c0d44c14512b0714fa8f1aeb31343637373535373536</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>88c355e8747a43a11ab58c77568ef194e8d4c7ab</challenge>

tx  <response>31f156a960d603050a4a1f3b9d0c83a08733c7687a069d6ed875b94602b9c90c7080e40b04a929869354e052eb62984ade2a92adbb0ff9e1029390a4249f895f548868c8b8171620aeaf5c64b354</response>

rx  <success t="1467755756" props="5" kind="free" status="active" creation="1467755016" expiration="4444444444">0339ca64230934d7195423920ba5a8f153233a8b</success>

tx  <presence name="Gabriel" type="available"></presence>

tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="3" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="4" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <presence from="573012919665@s.whatsapp.net"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

tx  <iq to="s.whatsapp.net" type="set" id="5" xmlns="status">
tx    <status>Para el hombre honrado las deudas son una amarga esclavitud. </status>
tx  </iq>

Estado actualizado: Para el hombre honrado las deudas son una amarga esclavitud.  
rx  <iq from="573012919665@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="573012919665@s.whatsapp.net" type="error" id="3">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="error" id="4">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="5"></iq>

rx  <iq from="s.whatsapp.net" type="error" id="2">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="6" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="6" t="1467755828"></iq>

rx  <presence from="573208665605@s.whatsapp.net"></presence>

tx  <iq id="7" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="7" t="1467755916"></iq>

rx  <presence from="573185219336@s.whatsapp.net"></presence>

rx  <chatstate from="573185219336@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="573185219336@s.whatsapp.net" type="text" id="C722C8DDFEDE29F58BA1A26E4BC25B" t="1467755934" notify="Jorge Díaz">
rx    <enc v="2" type="pkmsg">3308b0b74f1221053559048108bc11b383e655d9e13cb55f028e0306170a63fe5a139c6ea2defb461a2105f8e256d78e917ee5836bc349b17f3516dc7b209a80e74799345f493688ee810f2242330a21050fd7afa8a9c48152fe89c2d086457cd46dcddaa54acfaa184fe968512bf2f9411000180022106679522f873a092d3fdc590fa5f56cc75311aead419b057a28b1fdf7df0730ee30</enc>
rx  </message>

tx  <ack to="573185219336@s.whatsapp.net" class="message" id="C722C8DDFEDE29F58BA1A26E4BC25B" t="1467755934"></ack>

tx  <iq id="8" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="573185219336@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="8">
rx    <list>
rx      <user jid="573185219336@s.whatsapp.net">
rx        <registration>7bfdfeb1</registration>
rx        <type>05</type>
rx        <identity>f8e256d78e917ee5836bc349b17f3516dc7b209a80e74799345f493688ee810f</identity>
rx        <skey>
rx          <id>000000</id>
rx          <value>e9fdecb637acbf991e66918977be85cf45956cf0c478d2b8c4916eb5b83bc301</value>
rx          <signature>e54d08a86b62c588fb6fac0d8c3f3ce94f7ad39093007a675c3dd27ad7ec2612abbc04531177c9b8a4fdad9642f52ad7efd2da34113c8ae571be477d9cc66a00</signature>
rx        </skey>
rx        <key>
rx          <id>5aabb5</id>
rx          <value>74b4a978f5eda7607d62378b665e1a1c38042380fcf07a5c07117d4a8de62a51</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

tx  <ack to="573185219336@s.whatsapp.net" class="message" id="C722C8DDFEDE29F58BA1A26E4BC25B" t="1467755934"></ack>


-> Decrypted Message: Hola

tx  <receipt type="read" to="573185219336@s.whatsapp.net" id="C722C8DDFEDE29F58BA1A26E4BC25B" t="1467755934"></receipt>

Entrada filtrada: hola 4
Agregando nuevo contacto +573185219336 
tx  <iq id="9" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_032cb6cb-3eca-4d8d-9aea-dae390e7cf90" index="0" last="true">
tx      <user>+573185219336</user>
tx    </sync>
tx  </iq>

rx  <ack from="573185219336@s.whatsapp.net" class="receipt" type="read" id="C722C8DDFEDE29F58BA1A26E4BC25B"></ack>

rx  <chatstate from="573185219336@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="573185219336@s.whatsapp.net" type="text" id="9FE7665AE3FAAA1147DC7D317E3EFA" t="1467755945" notify="Jorge Díaz">
rx    <enc v="2" type="pkmsg">3308b0b74f1221053559048108bc11b383e655d9e13cb55f028e0306170a63fe5a139c6ea2defb461a2105f8e256d78e917ee5836bc349b17f3516dc7b209a80e74799345f493688ee810f2252330a21050fd7afa8a9c48152fe89c2d086457cd46dcddaa54acfaa184fe968512bf2f9411001180022207556ca4cb9521ad6319b2bb0ca8f0cbc856f49458f6aa1109de8d32996a7d2821b7251ab21afbc6f28b1fdf7df0730ee30</enc>
rx  </message>

tx  <ack to="573185219336@s.whatsapp.net" class="message" id="9FE7665AE3FAAA1147DC7D317E3EFA" t="1467755945"></ack>


-> Decrypted Message: Como estas?????

tx  <receipt type="read" to="573185219336@s.whatsapp.net" id="9FE7665AE3FAAA1147DC7D317E3EFA" t="1467755945"></receipt>

Entrada filtrada: como estas????? 15
rx  <ack from="573185219336@s.whatsapp.net" class="receipt" type="read" id="9FE7665AE3FAAA1147DC7D317E3EFA"></ack>

rx  <iq from="573012919665@s.whatsapp.net" type="result" id="9">
rx    <sync index="0" sid="sync_sid_full_032cb6cb-3eca-4d8d-9aea-dae390e7cf90" last="true" version="1467755946576745">
rx      <in>
rx        <user jid="573185219336@s.whatsapp.net">+573185219336</user>
rx      </in>
rx    </sync>
rx  </iq>

SyncResult Object
(
    [index] => 0
    [syncId] => sync_sid_full_032cb6cb-3eca-4d8d-9aea-dae390e7cf90
    [existing] => Array
        (
            [+573185219336] => 573185219336@s.whatsapp.net
        )

    [nonExisting] => Array
        (
        )

)
573185219336@s.whatsapp.net exists 
tx  <presence type="subscribe" to="+573185219336@s.whatsapp.net"></presence>

Contacto +573185219336 Agregado

tx  <receipt type="read" to="573185219336@s.whatsapp.net" id="C722C8DDFEDE29F58BA1A26E4BC25B" t="1467755934"></receipt>

Entrada filtrada: hola 4
rx  <presence from="+573185219336@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <chatstate from="573185219336@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <ack from="573185219336@s.whatsapp.net" class="receipt" type="read" id="C722C8DDFEDE29F58BA1A26E4BC25B"></ack>

rx  <message from="573185219336@s.whatsapp.net" type="text" id="F74F685642CACBF7E9EA3FC409B52C" t="1467755950" notify="Jorge Díaz">
rx    <enc v="2" type="pkmsg">3308b0b74f1221053559048108bc11b383e655d9e13cb55f028e0306170a63fe5a139c6ea2defb461a2105f8e256d78e917ee5836bc349b17f3516dc7b209a80e74799345f493688ee810f2252330a21050fd7afa8a9c48152fe89c2d086457cd46dcddaa54acfaa184fe968512bf2f9411002180022207d096def1220fabc8f37a75bf3d7d54c55923cf81a1693a41ad6de2a0b2fd0335d72344fa4724f1b28b1fdf7df0730ee30</enc>
rx  </message>

tx  <ack to="573185219336@s.whatsapp.net" class="message" id="F74F685642CACBF7E9EA3FC409B52C" t="1467755950"></ack>


-> Decrypted Message: Tengo una pregunta?

tx  <receipt type="read" to="573185219336@s.whatsapp.net" id="F74F685642CACBF7E9EA3FC409B52C" t="1467755950"></receipt>

Entrada filtrada: tengo una pregunta? 19
rx  <ack from="573185219336@s.whatsapp.net" class="receipt" type="read" id="F74F685642CACBF7E9EA3FC409B52C"></ack>

rx  <presence from="573208665605@s.whatsapp.net" type="unavailable" last="1467755967"></presence>

rx  <presence from="573185219336@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="573185219336@s.whatsapp.net"></presence>

rx  <presence from="573185219336@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="573185219336@s.whatsapp.net"></presence>

rx  <presence from="573185219336@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /opt/desarrollo/Chat-API/src/whatsprot.class.php:300
Stack trace:
#0 /opt/desarrollo/datacobro.php(106): WhatsProt->pollMessage()
#1 {main}
  thrown in /opt/desarrollo/Chat-API/src/whatsprot.class.php on line 300

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /opt/desarrollo/Chat-API/src/whatsprot.class.php:300
Stack trace:
#0 /opt/desarrollo/datacobro.php(106): WhatsProt->pollMessage()
#1 {main}
  thrown in /opt/desarrollo/Chat-API/src/whatsprot.class.php on line 300
```

Please helpme:

```php
$wa = new WhatsProt($sender, $nickname, TRUE);
$wa->connect();
$wa->loginWithPassword($password);

$wa->sendGetPrivacyBlockedList(); // Get our privacy list
$wa->sendGetClientConfig();

if($wp_primera_vez == "si"){


        $wa->sendGetServerProperties(); // Get server properties

        $wa->sendGetGroups(); // Get groups (participating)

        $wa->sendGetBroadcastLists(); // Get broadcasts lists



        $contactos = contactos($link);
        if(count($contactos > 0))
                $wa->sendSync($contactos);


        foreach ($contactos AS $contacto)
                  $wa->sendPresenceSubscription($contacto); // subscribe to the user



        $wa->sendGetStatuses($contactos);


        foreach ($contactos AS $contacto)
                $wa->sendGetProfilePicture($contacto); // preview profile picture of every contact


        $actualiza_configuracion_wp = mysql_query('UPDATE configuracion SET valor = "no" WHERE nombre = "wp_primera_vez"', $link);

}

$wa->pollMessage();
$wa->pollMessage();

$wa->eventManager()->bind("onGetMessage", "GetMessage");
$wa->eventManager()->bind('onGetSyncResult', 'onSyncResult');




# Actualizacion de estado y perfil
$wp_estado = $memcache->get("wp_estado");

if($wp_estado == ""){
        $wp_estado = obtener_estado($link);
        $wa->sendStatusUpdate($wp_estado);
        echo "Estado actualizado: $wp_estado \n";
}


if(count($argv) > 1)
 $wa->sendSetProfilePicture($argv[1]);


$espera = mt_rand(300,3600);
$tiempo_fuera = 0;

while($tiempo_fuera < $espera){
        eliminar($link, $wa);

        # No trabajar en estas horas
        $hora = date("H");
        if($hora > 21 || $hora < 7 )
                break;

        $wa->pollMessage();


        $tiempo_fuera = $tiempo_fuera++;
        sleep(2);
}

mysql_close($link);
$wa->disconnect();


function contactos($link){
        $consulta_txt = "SELECT usuario FROM wp_comercio ";

        $consulta = mysql_query($consulta_txt, $link)
                        OR error_sql("Error consultando contactos", $consulta_txt);

        while($info = mysql_fetch_assoc($consulta)){
                $contactos[] = "+".$info['usuario'];

        }
        mysql_free_result($consulta);

        foreach($contactos as $contacto){
                $sql = "INSERT INTO wp_sync(usuario) values('$contacto');";
                $inser = mysql_query($sql, $link)
                        OR error_sql("Error insertanto contactos wp_sync", $consulta_txt);
                }

        return $contactos;

}

function sincronizar_contacto($link, $wa, $dst){
        $dst = "+".$dst;

        $sql = "SELECT COUNT(*) AS existe FROM wp_sync WHERE usuario = '$dst'";
        $query = mysql_query($sql,$link)
                        OR error_sql("Error consultando si existe $dst en wp_sync", $sql);
        $info = mysql_fetch_assoc($query);

        if($info['existe'] == 1)
                return;


        $sql = "INSERT INTO wp_sync(usuario) values('$dst');";
        $query = mysql_query($sql,$link)
                        OR error_sql("Error creando $dst en wp_sync", $sql);

        echo "Agregando nuevo contacto $dst \n";
        sleep(10);

        $wa->sendSync($dst);
        $wa->sendPresenceSubscription($dst);

        echo "Contacto $dst Agregado\n\n";
        sleep(1);
}

function GetMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
        global $wa, $link, $tiempo_fuera, $conexionmc, $memcache;

        $tiempo_fuera = 0;


        $body = preg_replace('/( ){2,}/u',' ',$body);
        $body = strtolower($body);

        $body = quitar_acentos($body);

        $body = trim($body);

        $len = strlen($body);
        print("Entrada filtrada: $body $len\n");

        if(is_numeric($body))
                print("Entrada $body es numerica \n");

        $pos = strpos($from,"@");
        $dst = substr($from,0,$pos);

        sincronizar_contacto($link, $wa, $dst);

       $nombre = obtener_nombre($dst);

        $usuario_valido = usuario_valido($link, $dst);



       if(substr($body,0,4) == "ping"){
                $variables = array("nombre" => $nombre);
                escribir($wa,$dst,3,$variables);
                return;
        }



        if(!$usuario_valido){
                return;

        }


        if($usuario_valido){
                if(substr($body,0,5) == "ayuda"){
                        escribir($wa,$dst,10, array("nombre"=>$nombre));
                        return;
                        }

                # Comando invalido
                escribir($wa, $dst,22,array("nombre"=>$nombre));
                return;

        }

}
```

**Comment by davidsantanacosta** [comment]
I have the same problem my friend :(

**Comment by asluiz** [comment]
Same here. I had a number which I was using for more than 6 months, without problem, then, out of the blue, it was blocked. 

So, I purchased another SIM card, updated all the code, and was blocked in 5 minutes.

I'm polling, composing, syncing, everything is very compatible with a human behaviour...

**Comment by edudesouza** [comment]
Look at how you are connecting, though an ISP, Mobile Carrier ... Changes are, if you are using a vps or any hosting service, media temple, host gator, and similars you will get blocked.


via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.40&pv=4.3&source=email_footer_2] On Wed, Jul 06, 2016 at 3:58 PM, asluiz < notifications@github.com [notifications@github.com] > wrote:
Same here. I had a number which I was using for more than 6 months, without problem, then, out of the blue, it was blocked.

So, I purchased another SIM card, updated all the code, and was blocked in 5 minutes.

I'm polling, composing, syncing, everything is very compatible with a human behaviour...

**Comment by mgp25** [comment]
Probably they noticed its an automated stuff - non human behavior

Regards

**Comment by davidsantanacosta** [comment]
Ok... But my question is.. The wiki has any example that has human behavior or can you explain if that code have something wrong?

**Comment by alemdg** [comment]
there is no example, this is pure crap.... 

"automated stuff" ?, 

put a damn example of "what you call" human behavior
