### ISSUE TITLE
Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed

### ISSUE THREAD

**Issue by nextvikas** [mgp25/Chat-API#2159]
Warning: socket_connect(): Host lookup failed [-10002]: Host name lookup failure in /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php on line 175
tx  <stream:features></stream:features>

tx  <auth user="919781874126" mechanism="WAUTH-2">565fb946393139373831383734313236de57b35f0f1ee823077d3b2b5d54367b3c7fbf6131343739383935373335</auth>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php:300 Stack trace: #0 /opt/lampp/htdocs/Chat-API-master/src/Login.php(40): WhatsProt->pollMessage() #1 /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php(287): Login->doLogin() #2 /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php(324): WhatsProt->loginWithPassword('PVhrQonHC7b3BQc...') #3 /opt/lampp/htdocs/Chat-API-master/src/Login.php(49): WhatsProt->pollMessage() #4 /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php(287): Login->doLogin() #5 /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php(324): WhatsProt->loginWithPassword('PVhrQonHC7b3BQc...') #6 /opt/lampp/htdocs/Chat-API-master/src/Login.php(49): WhatsProt->pollMessage() #7 /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php(287): Login->doLogin() #8 /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php(324): WhatsProt->loginWithPassword('PVhrQonHC7b3BQc...') #9 /opt/lampp/htdocs/C in /opt/lampp/htdocs/Chat-API-master/src/whatsprot.class.php on line 300

**Comment by nextvikas** [comment]
@mgp25 why close this issue?
