### ISSUE TITLE
I'm having trouble with eventManager someone help me?

### ISSUE THREAD

**Issue by Pudins** [mgp25/Chat-API#663]
The fact is I am trying to do so without success:
```php
$w->eventManager()->bind("onGetMessage","sendMsg");

function sendMSG($mynumber, $from, $id, $type, $time, $name, $body)
{
    $username = "****************";
    $password = "********************";
    $nickname = "**SharkTalks**";
    $debug = false;
    $w = new WhatsProt($username, $nickname, $debug);
    $w->sendMessage($from, "Hello I'm busy, as I talk to you! - " . date('H:i'));

}
```

To run this code it returns me this error:
```
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/ubuntu/Chat-API-master/src/whatsprot.class.php:548
Stack trace:
#0 /home/ubuntu/Chat-API-master/src/whatsprot.class.php(1959): WhatsProt->pollMessage()
#1 /home/ubuntu/Chat-API-master/src/whatsprot.class.php(3764): WhatsProt->waitForServer('-1')
#2 /home/ubuntu/Chat-API-master/src/whatsprot.class.php(1490): WhatsProt->sendMessageNode('***************@s....', Object(ProtocolNode), NULL)
```
I thank you for your help and for your time!

**Comment by CODeRUS** [comment]
Connection closed by server. Show your debug log.

**Comment by jesussales** [comment]
The number that recived is the same that you want to send a New message? ?

**Comment by mgp25** [comment]
@Pudins look at `waitForServer` what kind of id is `-1` redownload the API, you have done something wrong in there.

Regards
