### ISSUE TITLE
'Connection closed!'  when poll or send message

### ISSUE THREAD

**Issue by Incher25** [mgp25/Chat-API#728]
Hello to all,

I have two scripts, one of them listen for received messages (it runs every minute by cron):
```php
 $events = new MyEvents($w);
                        $events->setEventsToListenFor($events->activeEvents);
                        $w->Connect();
                        $w->loginWithPassword($password);
                        $w->sendGetServerProperties();
                        for ($i=0; $i<6; $i++) {
                                while ($w->pollMessage()) {
                                       $w->pollMessage();
                                        sleep(10);
                                }
                        }
```
and every minute I have error message in apache error.log:
```
[Mon May 18 09:40:08.084074 2015] [:error] [pid 13328] [client ...] PHP Fatal error:  Uncaught 
exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/whatsapi
/src/whatsprot.class.php:548\nStack trace:\n#0 /var/www/html/whatsapi/proc_messages.php(68): 
WhatsProt->pollMessage()\n#1 {main}\n  thrown in /var/www/html/whatsapi/src/whatsprot.class.php 
on line 548
```
Second script for sending messages:
```php
...
$target = array("phone1", "phone2", "phone3");
$message = "Тест рассылки WA - ".date("Y-m-d H:i:s", time()).". OK.";
foreach ($target as $t) {
        $w->Connect();
        $w->loginWithPassword($password);
        $messageId = "message-".$w->sendMessage($t , $message);
        $w->Disconnect();
}
```
Sometimes it works properly but sometimes i have the same error
```
[Sat May 16 09:50:02.717907 2015] [:error] [pid 18169] [client ...] PHP Fatal error:  Uncaught 
exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/whatsapi
/src/whatsprot.class.php:548\nStack trace:\n#0 /var/www/html/whatsapi
/src/whatsprot.class.php(1977): WhatsProt->pollMessage()\n#1 /var/www/html/whatsapi
/src/whatsprot.class.php(3837): WhatsProt->waitForServer('1431733802-1')\n#2 /var/www
/html/whatsapi/src/whatsprot.class.php(1488): WhatsProt->sendMessageNode('...', 
Object(ProtocolNode), NULL)\n#3 /var/www/html/whatsapi/send_wa_status.php(20): 
WhatsProt->sendMessage('...', '???????? ??????...')\n#4 {main}\n  thrown in /var/www
/html/whatsapi/src/whatsprot.class.php on line 548
```
 and I don't know what it depends on. 
I tried to apply recommendations from https://github.com/mgp25/Chat-API/issues/192 but it still doesn't work.

Thanks in advance!

**Comment by CODeRUS** [comment]
show debug log

**Comment by Incher25** [comment]
```
tx&nbsp;&nbsp;&lt;stream:features&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;readreceipts&gt;&lt;
/readreceipts&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;groups_v2&gt;&lt;/groups_v2&gt;<br />
tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;privacy&gt;&lt;/privacy&gt;<br />
tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;presence&gt;&lt;/presence&gt;<br />tx&nbsp;&nbsp;&lt;/stream:features&gt;<br /><br />
tx&nbsp;&nbsp;&lt;auth mechanism="WAUTH-2" user="XXXXXXXXXXX"&
gt;�y�XXXXXXXXXXX0z̄|?��X��'/*����j1431908394&lt;/auth&gt;<br /><br />
rx&nbsp;&nbsp;&lt;start from="s.whatsapp.net"&gt;&lt;/start&gt;<br /><br />
rx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
rx&nbsp;&nbsp;&lt;challenge&gt;�1Ϳ6�6c����j�~U[&lt;/challenge&gt;<br /><br />
tx&nbsp;&nbsp;&lt;response&gt;	)�DQ�ҵ�_�Z`J���4au�_��^6��&lt;/response&gt;<br /><br />
rx&nbsp;&nbsp;&lt;success t="1431908395" props="4" kind="free" status="active" creation="1415595112" expiration="1447131112"&gt;##����.���%h���&lt;/success&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence name="test"&gt;&lt;/presence&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="1431908395-1" type="get" xmlns="w" to="s.whatsapp.net"&gt;<br />
tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;props&gt;&lt;/props&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;ib from="s.whatsapp.net"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;offline 
count="0"&gt;&lt;/offline&gt;<br />rx&nbsp;&nbsp;&lt;/ib&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="XXXXXXXXXXX@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="YYYYYYYYYYY@s.whatsapp.net" type="unavailable" 
last="1431908391"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="s.whatsapp.net" id="1431908395-1" type="result"&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;props version="4"&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="timeout" value="300"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="location" value="0"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="readreceipts" value="1415214000"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="qr" value="0"&gt;&lt;/prop&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="groups_v2" value="1"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="lists" value="1"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="library" value="0"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="audio" value="1"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="checkmarks" value="0"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="newmedia" value="0"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="video_max_edge" value="960"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="image_max_kbytes" value="5120"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="image_quality" value="80"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="image_max_edge" value="1280"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="media" value="16"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="broadcast" value="50"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="max_subject" value="25"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="max_participants" value="101"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;prop name="max_groups" value="9999"&gt;&lt;/prop&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;/props&gt;<br />rx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;presence from="YYYYYYYYYYY@s.whatsapp.net"&gt;&lt;/presence&gt;<br /><br />
rx&nbsp;&nbsp;&lt;stream:error&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;conflict&gt;&lt;/conflict&gt;<br />
rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;text&gt;Replaced by new connection&lt;/text&gt;<br />
rx&nbsp;&nbsp;&lt;/stream:error&gt;<br /><br />
```

**Comment by CODeRUS** [comment]
Replaced by new connection
you have multiple connections of your number. you should keep one single connection active and use it for sending and receiving messages.

**Comment by Incher25** [comment]
is it right to check $w->isConnected(); before use $w->Connect(); to keep single connection?

**Comment by CODeRUS** [comment]
no, this function is returning own instance state, not any other.

**Comment by Incher25** [comment]
so how can I check is it connected?

**Comment by CODeRUS** [comment]
you can't do it. from current script you can get connected state onnly of current script :)

**Comment by Incher25** [comment]
Ok :) thanks for help
