### ISSUE TITLE
Connection Closed after 3-4 minutes

### ISSUE THREAD

**Issue by billa316** [mgp25/Chat-API#763]
Hi,

I tested using the whatsapp.php under tests. When listening to the messages, "php whatsapp.php -l", after like 3-4 minutes the Connection gets terminated. Below is the error message:

"Fatal error: Uncaught exception 'ConnectionException' with message 'Connection C
losed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 557

ConnectionException: Connection Closed! in C:\wamp\www\whatsappAPI\src\whatsprot
.class.php on line 557"

Line 557 is the pollMessage function.

Any idea how this can be resolved?

**Comment by mgp25** [comment]
debug log?

**Comment by billa316** [comment]
@mgp25 The debug log as below:

"
)
rx  <stream:error>
rx    <ack></ack>
rx  </stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connect
ion Closed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php:558
Stack trace:
#0 C:\wamp\www\whatsappAPI\tests\whatsapp.php(93): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 558

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection C
losed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 558

ConnectionException: Connection Closed! in C:\wamp\www\whatsappAPI\src\whatsprot
.class.php on line 558

Call Stack:
    0.0006     361200   1. {main}() C:\wamp\www\whatsappAPI\tests\whatsapp.php:0

   62.3293    2236080   2. WhatsProt->pollMessage() C:\wamp\www\whatsappAPI\test
s\whatsapp.php:93

"

**Comment by mgp25** [comment]
this was fixed in latest releases

Regards

**Comment by billa316** [comment]
Hi,

But I downloaded the latest version today and tried but am facing the same issue.

**Comment by mgp25** [comment]
@billa316 post full debug log

**Comment by billa316** [comment]
How do i get the full debug log?

Below is what I am getting from the command prompt when running the whatsapp.php from tests

```
rx  <stream:error>
rx    <ack></ack>
rx  </stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connect
ion Closed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php:555
Stack trace:
#0 C:\wamp\www\whatsappAPI\tests\whatsapp.php(88): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 555

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection C
losed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 555

ConnectionException: Connection Closed! in C:\wamp\www\whatsappAPI\src\whatsprot
.class.php on line 555

Call Stack:
    0.0006     359528   1. {main}() C:\wamp\www\whatsappAPI\tests\whatsapp.php:0

   65.7640    2242952   2. WhatsProt->pollMessage() C:\wamp\www\whatsappAPI\test
s\whatsapp.php:88
```

**Comment by mgp25** [comment]
@billa316 there should be more above the stream error

**Comment by billa316** [comment]
Above the stream error is the intercepted message. The full log is as below:

```
rx  <message from="1234567890@s.whatsapp.net" id="1324576890-12" type="text" t="
1628742987" notify="Test">
rx    <body>I wanna prove myself</body>
rx  </message>

Array
(
    [0] => ProtocolNode Object
        (
            [tag:ProtocolNode:private] => message
            [attributeHash:ProtocolNode:private] => Array
                (
                    [from] => 1234567890@s.whatsapp.net
                    [id] => 1324576890-12
                    [type] => text
                    [t] => 1628742987
                    [notify] => Test
                )

            [children:ProtocolNode:private] => Array
                (
                    [0] => ProtocolNode Object
                        (
                            [tag:ProtocolNode:private] => body
                            [attributeHash:ProtocolNode:private] => Array
                                (
                                )

                            [children:ProtocolNode:private] =>
                            [data:ProtocolNode:private] => I wanna prove myself
                        )

                )

            [data:ProtocolNode:private] =>
        )

)
rx  <stream:error>
rx    <ack></ack>
rx  </stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connect
ion Closed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php:555
Stack trace:
#0 C:\wamp\www\whatsappAPI\tests\whatsapp.php(88): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 555

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection C
losed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 555

ConnectionException: Connection Closed! in C:\wamp\www\whatsappAPI\src\whatsprot
.class.php on line 555

Call Stack:
    0.0006     359528   1. {main}() C:\wamp\www\whatsappAPI\tests\whatsapp.php:0

   65.7640    2242952   2. WhatsProt->pollMessage() C:\wamp\www\whatsappAPI\test
s\whatsapp.php:88

```

**Comment by mgp25** [comment]
@billa316 there should be more and more, from the login to the error i need

**Comment by billa316** [comment]
@mgp25 

Below is the full output from login:

```
c:\wamp\www\whatsappAPI\tests>php whatsapp.php -l
PHP Notice:  Undefined offset: 2 in C:\wamp\www\whatsappAPI\tests\whatsapp.php o
n line 35
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\whatsappAPI\tests\whatsapp.php:0

Notice: Undefined offset: 2 in C:\wamp\www\whatsappAPI\tests\whatsapp.php on lin
e 35

Call Stack:
    0.0006     359528   1. {main}() C:\wamp\www\whatsappAPI\tests\whatsapp.php:0


[] Logging in as 'Tezt' (1234567890)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="1234567890">+¯¬÷1234567890O+F·»çPe¦(c+=:É¬Z+
ç»1432778833</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>¬Ä»S+B+n¦<µ¤q9rü=?+.</challenge>

tx  <response>-[Vs+Ö{ög|¦Gd¦#?ge¢¦dCijCk¦v?Z¦â¯Æ</response>

rx  <success t="1431234539" props="4" kind="free" status="active" creation="1430
793307" expiration="1465432107">\=íìm?tTO?jò+ZBMd+?¦</success>

tx  <presence name="Tezt"></presence>

tx  <presence type="inactive"></presence>


[] Listen mode:
rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="1234567890@s.whatsapp.net"></presence>

rx  <presence from="7327893450@s.whatsapp.net"></presence>

rx  <presence from="1234567890@s.whatsapp.net" type="unavailable"></presence>

rx  <message from="7327893450@s.whatsapp.net" id="1409876524-63" type="text" t="
1436328957" notify="Z">
rx    <body>Test</body>
rx  </message>

Array
(
    [0] => ProtocolNode Object
        (
            [tag:ProtocolNode:private] => message
            [attributeHash:ProtocolNode:private] => Array
                (
                    [from] => 7327893450@s.whatsapp.net
                    [id] => 1409876524-63
                    [type] => text
                    [t] => 1436328957
                    [notify] => Z
                )

            [children:ProtocolNode:private] => Array
                (
                    [0] => ProtocolNode Object
                        (
                            [tag:ProtocolNode:private] => body
                            [attributeHash:ProtocolNode:private] => Array
                                (
                                )

                            [children:ProtocolNode:private] =>
                            [data:ProtocolNode:private] => Test
                        )

                )

            [data:ProtocolNode:private] =>
        )

)
rx  <stream:error>
rx    <ack></ack>
rx  </stream:error>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connect
ion Closed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php:555
Stack trace:
#0 C:\wamp\www\whatsappAPI\tests\whatsapp.php(88): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 555

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection C
losed!' in C:\wamp\www\whatsappAPI\src\whatsprot.class.php on line 555

ConnectionException: Connection Closed! in C:\wamp\www\whatsappAPI\src\whatsprot
.class.php on line 555

Call Stack:
    0.0006     359528   1. {main}() C:\wamp\www\whatsappAPI\tests\whatsapp.php:0

   80.6795    2242920   2. WhatsProt->pollMessage() C:\wamp\www\whatsappAPI\test
s\whatsapp.php:88
```

**Comment by billa316** [comment]
Ok i found others also had the same issue. One way I tested and is working is if the connection dies, reconnect again like:

```
while (1) {
	  if (!$wa->isConnected()) {
		$wa->connect();
		$wa->loginWithPassword($password);
	  }

	  try {
		$wa->pollMessage();
		  $data = $wa->getMessages();
        if (!empty($data)) {
           print_r($data);
        }
		sleep(1);
	  }
	  catch(Exception $e) {
		$wa->disconnect();
	  }
	}
    exit(0);
```

**Comment by billa316** [comment]
Ok i found others also had the same issue as reported previously. One way I tested and is working is if the connection dies, reconnect again like:

```
while (1) {
      if (!$wa->isConnected()) {
        $wa->connect();
        $wa->loginWithPassword($password);
      }

      try {
        $wa->pollMessage();
          $data = $wa->getMessages();
        if (!empty($data)) {
           print_r($data);
        }
        sleep(1);
      }
      catch(Exception $e) {
        $wa->disconnect();
      }
    }
    exit(0);

```
Not sure if there is another way to ensure that the connection doesn't die in the first place for a more elegant solution.
